### ISSUE TITLE
Unity version

### ISSUE THREAD

**Issue by cemuka** [Eraclys/BehaviourTree#1]
This project looks very promising and I wonder if you could make a unity project version?

**Comment by MilianL** [comment]
Hey there

Thank you for your interest

What do you mean by a unity project version?

This library targets .NET standard 1.0 which i believe is compatible with unity? https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by ghost** [comment]
Hey there

Thank you for your interest

What do you mean by a unity project version?

This library targets .NET standard 1.0 which i believe is compatible with unity? https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by cemuka** [comment]
It works, yeah but It wouldn't be integrated with unity, without unity components and a scene.

What I mean is that for example using unity Update and Time to depended on frame rate, using Transform for position and rotation values.

**Comment by ghost** [comment]
Quite frankly I'm not very familiar with Unity  :(

One of the main aim of this project is to be decoupled from any third party library. So if unity support is added it should be as an extension of this library. 

I'm currently not in a position to be able to look into it. However if you have some solution and would like to submit a PR, I'd be happy to check it out :)

**Comment by cemuka** [comment]
Hey thats great, I'll look into it 👍
